export const content = {
    login: 'LOG IN',
    letsSignIn: 'Let’s Sign in',
    welcomeBack: 'Welcome back, You’ve been missed!',
    enterUserName: 'Please enter a user name',
    passwordRequired: 'Password is required',
    passwordMinChar: 'Password should be minimum 6 characters',
    passwordSpaces: 'Password cannot contain spaces',
    attendance: 'Attendance',
    timeTable: 'Timetable',
    complain: 'Complain Box',
    exam: 'Exam',
    result: 'Results',
    holiday: 'Holidays',
    events: 'Events',
    fees: 'Fees',
    materials: 'Materials',
    privacyPolicy: 'Privacy policy',
    termsConditions: 'Terms & Conditions',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    rateUs: 'Rate Us',
    share: 'Share',
    homeWork: 'Home Work',
    notifications: 'Notifications',
    logout: 'LOG OUT ?'
}